import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choose weights you need
  variable: '--font-open-sans', // optional CSS variable
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className=" relative ">

        <div className="min-h-screen w-full  bg-[#0a0a0a] relative   ">
          <div
            className="fixed inset-0 z-0"
            style={{
              backgroundImage: `radial-gradient(circle 500px at 50% 200px, #0a1d2e, transparent)`,
            }}
          />
          <Header />
          <div className="flex relative py-20 mx-48 ">

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
